const alex = {
    masterAccess: `1`,
    access: `19032019234`,
    stage: `pending`,
    name: `ALEX`,
    lastName: `SMITH`,
    received: 1551736800000,
    tray: `it's tray`,
    speci: `it's speci`,
    dob: 381877200000,
    sex: `MALE`,
    client: `22 MOLIVER VLADIMIR`,
    physician: `Moliver, Vladimir DR`,
    requisitionPdf: `https://google.com`,
    diagnosis: `[{"code":"z.004","description":"Encounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findings"},{"code":"z.005","description":"Encounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findings"}]`,
    patientHistory: `Post Partum`,
    lmpDate: 994885200000,
    routineScreen: true,
    abnormalBleeding: null,
    highRisk: true,
    discharge: true,
    previousDysplasia: null,
    hysterectomy: null,
    vaginitis: null,
    radiationTherapy: true,
    iudInplace: null,
    hrt: null,
    yearsMenopausal: 4,
    previousPapDate: 1366059600000,
    previousPapDiagnosis: `LSIL`,
    specimenSource: `Cervix`,
    specimenReceived: `Thinprep Vial`,
    instrumFirst: `Centrifuge #2`,
    instrumSecond: `Hologic Imager`,
}

const samanta = {
    masterAccess: `2`,
    access: `19032019275`,
    stage: `pending`,
    name: `SAMANTA`,
    lastName: `BLACK`,
    received: 1368910800000,
    tray: `it's tray`,
    speci: `it's speci`,
    dob: 536446800000,
    sex: `FEMALE`,
    client: `22 MOLIVER VLADIMIR`,
    physician: `Moliver, Vladimir DR`,
    requisitionPdf: `https://google.com`,
    diagnosis: `[{"code":"c.017","description":"Encounter for general adult medical "},{"code":"b.044","description":"Adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal for general adult medical examination without abnormal findings"}]`,
    patientHistory: `Post Partum`,
    lmpDate: 1365886800000,
    routineScreen: null,
    abnormalBleeding: null,
    highRisk: null,
    discharge: null,
    previousDysplasia: true,
    hysterectomy: true,
    vaginitis: null,
    radiationTherapy: true,
    iudInplace: null,
    hrt: null,
    yearsMenopausal: null,
    previousPapDate: 1366059600000,
    previousPapDiagnosis: `AGC`,
    specimenSource: `Vaginal`,
    specimenReceived: `Conventional Smear`,
    other: `Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...`,
    instrumFirst: null,
    instrumSecond: null,
}

const vivi = {
    masterAccess: `3`,
    access: `19032019111`,
    stage: `pending`,
    name: `VIVI`,
    lastName: `WHITE`,
    received: 1368910800000,
    tray: `it's tray`,
    speci: `it's speci`,
    dob: 536446800000,
    sex: `FEMALE`,
    client: `22 MOLIVER VLADIMIR`,
    physician: `Moliver, Vladimir DR`,
    requisitionPdf: `https://google.com`,
    diagnosis: `[{"code":"c.017","description":"Encounter for general adult medical "},{"code":"b.044","description":"Adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal for general adult medical examination without abnormal findings"}]`,
    source: `Urine`,
    receivedSource: `Specimen Cup`,
    ml: `3`,
    turbidity: `Clear`,
    color: `Yellow`,
    specType: `Fluid`,
    fixative: `Alcohol`,
    slideType: `ThinPrep`,
    grossOther: `Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...`,
    instrumFirst: null,
    instrumSecond: null,
}

const coco = {
    masterAccess: `4`,
    access: `19032019222`,
    stage: `pending`,
    name: `COCO`,
    lastName: `CHACHA`,
    received: 1368910800000,
    tray: `it's tray`,
    speci: `it's speci`,
    dob: 536446800000,
    sex: `FEMALE`,
    client: `22 MOLIVER VLADIMIR`,
    physician: `Moliver, Vladimir DR`,
    requisitionPdf: `https://google.com`,
    diagnosis: `[{"code":"c.017","description":"Encounter for general adult medical "},{"code":"b.044","description":"Adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal for general adult medical examination without abnormal findings"}]`,
    source: null,
    receivedSource: null,
    ml: null,
    turbidity: null,
    color: null,
    specType: null,
    fixative: null,
    slideType: null,
    instrumFirst: null,
    instrumSecond: null,
}

const soso = {
    masterAccess: `41`,
    access: `19032019374`,
    stage: `pending`,
    name: `SOSO`,
    lastName: `KOKO`,
    received: 1368910800000,
    tray: `it's tray`,
    speci: `it's speci`,
    dob: 536446800000,
    sex: `FEMALE`,
    client: `22 MOLIVER VLADIMIR`,
    physician: `Moliver, Vladimir DR`,
    requisitionPdf: `https://google.com`,
    diagnosis: `[{"code":"c.017","description":"Encounter for general adult medical "},{"code":"b.044","description":"Adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal for general adult medical examination without abnormal findings"}]`,
    source: null,
    receivedSource: null,
    ml: null,
    turbidity: null,
    color: null,
    specType: null,
    fixative: null,
    slideType: null,
    instrumFirst: null,
    instrumSecond: null,
}

const lala = {
    masterAccess: `43`,
    access: `19032019301`,
    stage: `pending`,
    name: `LALA`,
    lastName: `SASA`,
    received: 1368910800000,
    tray: `it's tray`,
    speci: `it's speci`,
    dob: 536446800000,
    sex: `FEMALE`,
    client: `22 MOLIVER VLADIMIR`,
    physician: `Moliver, Vladimir DR`,
    requisitionPdf: `https://google.com`,
    diagnosis: `[{"code":"c.017","description":"Encounter for general adult medical "},{"code":"b.044","description":"Adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal for general adult medical examination without abnormal findings"}]`,
    source: null,
    receivedSource: null,
    ml: null,
    turbidity: null,
    color: null,
    specType: null,
    fixative: null,
    slideType: null,
    instrumFirst: null,
    instrumSecond: null,
}

const toto = {
    masterAccess: `454`,
    access: `19032019390`,
    stage: `pending`,
    name: `TOTO`,
    lastName: `OTTO`,
    received: 1368910800000,
    tray: `it's tray`,
    speci: `it's speci`,
    dob: 536446800000,
    sex: `FEMALE`,
    client: `22 MOLIVER VLADIMIR`,
    physician: `Moliver, Vladimir DR`,
    requisitionPdf: `https://google.com`,
    diagnosis: `[{"code":"c.017","description":"Encounter for general adult medical "},{"code":"b.044","description":"Adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal for general adult medical examination without abnormal findings"}]`,
    source: null,
    receivedSource: null,
    ml: null,
    turbidity: null,
    color: null,
    specType: null,
    fixative: null,
    slideType: null,
    instrumFirst: null,
    instrumSecond: null,
}

const caca = {
    masterAccess: `455`,
    access: `19032019117`,
    stage: `pending`,
    name: `CACA`,
    lastName: `POPO`,
    received: 1368910800000,
    tray: `it's tray`,
    speci: `it's speci`,
    dob: 536446800000,
    sex: `FEMALE`,
    client: `22 MOLIVER VLADIMIR`,
    physician: `Moliver, Vladimir DR`,
    requisitionPdf: `https://google.com`,
    diagnosis: `[{"code":"c.017","description":"Encounter for general adult medical "},{"code":"b.044","description":"Adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal for general adult medical examination without abnormal findings"}]`,
    source: null,
    receivedSource: null,
    ml: null,
    turbidity: null,
    color: null,
    specType: null,
    fixative: null,
    slideType: null,
    instrumFirst: null,
    instrumSecond: null,
}

module.exports = {
    alex,
    samanta,
    vivi,
    coco,
    soso,
    toto,
    caca,
    lala
}