const alex = {
    masterAccess: `1`,
    access: `19032019234`,
    stage: `pending`,
    name: `ALEX, SMITH`,
    received: 1551736800000,
    tray: `it's tray`,
    speci: `it's speci`,
    dob: 381877200000,
    sex: `MALE`,
    client: `22 MOLIVER VLADIMIR`,
    physician: `Moliver, Vladimir DR`,
    requisitionPdf: `https://google.com`,
    diagnosis: `{"d":[{"code":"z.004","text":"Encounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findings"},{"code":"z.005","text":"Encounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findings"}]}`,
    patientHistory: `Post Partum`,
    lmpDate: 994885200000,
    routineScreen: true,
    abnormalBleeding: null,
    highRisk: true,
    discharge: true,
    previousDysplasia: null,
    hysterectomy: null,
    vaginitis: null,
    radiationTherapy: true,
    iudInplace: null,
    hrt: null,
    yearsMenopausal: 4,
    previousPapDate: 1366059600000,
    previousPapDiagnosis: `LSIL`,
    specimenSource: `Cervix`,
    specimenReceived: `Thinprep Vial`,
    other: `This is the random comment text`
}

const samanta = {
    masterAccess: `2`,
    access: `19032019275`,
    stage: `pending`,
    name: `SAMANTA, BLACK`,
    received: 1368910800000,
    tray: `it's tray`,
    speci: `it's speci`,
    dob: 536446800000,
    sex: `FEMALE`,
    client: `22 MOLIVER VLADIMIR`,
    physician: `Moliver, Vladimir DR`,
    requisitionPdf: `https://google.com`,
    diagnosis: `{"d":[{"code":"z.004","text":"Encounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findings"},{"code":"z.005","text":"Encounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findingsýEncounter for general adult medical examination without abnormal findings"}]}`,
    patientHistory: `Post Partum`,
    lmpDate: 1365886800000,
    routineScreen: null,
    abnormalBleeding: null,
    highRisk: null,
    discharge: null,
    previousDysplasia: true,
    hysterectomy: true,
    vaginitis: null,
    radiationTherapy: true,
    iudInplace: null,
    hrt: null,
    yearsMenopausal: null,
    previousPapDate: 1366059600000,
    previousPapDiagnosis: `AGC`,
    specimenSource: `Vaginal`,
    specimenReceived: `Conventional Smear`,
    other: `Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...`
}

module.exports = {
    alex,
    samanta
}